name: flutter_frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“¦ Paquetes esenciales
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.2.1
  intl: ^0.19.0

  # ðŸ“¦ Seguridad y sesiones
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # ðŸ“¦ Upload / Archivos
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  path: ^1.9.0

  # ðŸ“¦ UI / Utilidades
  expandable: ^5.0.1
  fluttertoast: ^8.2.4
  dio: ^5.4.0

  # ðŸ“„ PDF Y EXPORTACIÃ“N
  pdf: ^3.10.4
  printing: ^5.12.0

  # ðŸ”— Abrir links / PDFs (CV)
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
